import dayjs from 'dayjs'

export const MOCK_MENUS = {
  1: [
    {
      createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
      icon: 'setting',
      id: 1,
      path: '/system',
      redirect: '/system/user',
      name: '系统管理',
      componentName: 'System',
      type: 1,
      sort: 6,
      status: 0,
      parentId: 0,
      children: [
        {
          createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
          icon: 'houseUser',
          id: 10,
          path: 'tenant',
          name: '租户管理',
          componentName: 'SystemTenant',
          type: 1,
          sort: 1,
          status: 0,
          parentId: 1,
          children: [
            {
              component: 'system/tenant/list/index',
              createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
              icon: 'house',
              id: 11,
              path: 'list',
              name: '租户列表',
              componentName: 'SystemTenantList',
              type: 2,
              sort: 1,
              status: 0,
              parentId: 10,
              children: [
                {
                  'id': 1139,
                  'name': '租户查询',
                  'permission': 'system:tenant:query',
                  'type': 3,
                  'sort': 1,
                  'parentId': 11,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': null,
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1639456304000
                },
                {
                  'id': 1140,
                  'name': '租户创建',
                  'permission': 'system:tenant:create',
                  'type': 3,
                  'sort': 2,
                  'parentId': 11,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': null,
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1639456304000
                },
                {
                  'id': 1141,
                  'name': '租户更新',
                  'permission': 'system:tenant:update',
                  'type': 3,
                  'sort': 3,
                  'parentId': 11,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': null,
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1639456304000
                },
                {
                  'id': 1142,
                  'name': '租户删除',
                  'permission': 'system:tenant:delete',
                  'type': 3,
                  'sort': 4,
                  'parentId': 11,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': null,
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1639456304000
                },
                {
                  'id': 1143,
                  'name': '租户导出',
                  'permission': 'system:tenant:export',
                  'type': 3,
                  'sort': 5,
                  'parentId': 11,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': null,
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1639456304000
                },
                {
                  'id': 5010,
                  'name': '租户切换',
                  'permission': 'system:tenant:visit',
                  'type': 3,
                  'sort': 999,
                  'parentId': 11,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': '',
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1746429932000
                }
              ]
            },
            {
              component: 'system/tenant/package/index',
              createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
              icon: 'lines',
              id: 12,
              path: 'package',
              name: '租户套餐',
              componentName: 'SystemTenantPackage',
              type: 2,
              sort: 2,
              status: 0,
              parentId: 10,
              children: [
                {
                  'id': 1226,
                  'name': '租户套餐查询',
                  'permission': 'system:tenant-package:query',
                  'type': 3,
                  'sort': 1,
                  'parentId': 12,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': null,
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1645263846000
                },
                {
                  'id': 1227,
                  'name': '租户套餐创建',
                  'permission': 'system:tenant-package:create',
                  'type': 3,
                  'sort': 2,
                  'parentId': 12,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': null,
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1645263846000
                },
                {
                  'id': 1228,
                  'name': '租户套餐更新',
                  'permission': 'system:tenant-package:update',
                  'type': 3,
                  'sort': 3,
                  'parentId': 12,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': null,
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1645263846000
                },
                {
                  'id': 1229,
                  'name': '租户套餐删除',
                  'permission': 'system:tenant-package:delete',
                  'type': 3,
                  'sort': 4,
                  'parentId': 12,
                  'path': '',
                  'icon': '',
                  'component': '',
                  'componentName': null,
                  'status': 0,
                  'visible': true,
                  'keepAlive': true,
                  'alwaysShow': true,
                  'createTime': 1645263846000
                },
              ]
            },
          ]
        },
        {
          component: 'system/user/index',
          createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
          icon: 'user',
          id: 2,
          path: 'user',
          name: '用户管理',
          permission: 'system:user:list',
          componentName: 'SystemUser',
          type: 2,
          sort: 2,
          status: 0,
          parentId: 1,
          children: [
            {
              'id': 1001,
              'name': '用户查询',
              'permission': 'system:user:query',
              'type': 3,
              'sort': 1,
              'parentId': 2,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1002,
              'name': '用户新增',
              'permission': 'system:user:create',
              'type': 3,
              'sort': 2,
              'parentId': 2,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1003,
              'name': '用户修改',
              'permission': 'system:user:update',
              'type': 3,
              'sort': 3,
              'parentId': 2,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1004,
              'name': '用户删除',
              'permission': 'system:user:delete',
              'type': 3,
              'sort': 4,
              'parentId': 2,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1005,
              'name': '用户导出',
              'permission': 'system:user:export',
              'type': 3,
              'sort': 5,
              'parentId': 2,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1006,
              'name': '用户导入',
              'permission': 'system:user:import',
              'type': 3,
              'sort': 6,
              'parentId': 2,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1007,
              'name': '重置密码',
              'permission': 'system:user:update-password',
              'type': 3,
              'sort': 7,
              'parentId': 2,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            }
          ]
        },
        {
          component: 'system/role/index',
          createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
          icon: 'roleBinding',
          id: 3,
          path: 'role',
          name: '角色管理',
          componentName: 'SystemRole',
          type: 2,
          sort: 3,
          status: 0,
          parentId: 1,
          children: [
            {
              'id': 1008,
              'name': '角色查询',
              'permission': 'system:role:query',
              'type': 3,
              'sort': 1,
              'parentId': 3,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1009,
              'name': '角色新增',
              'permission': 'system:role:create',
              'type': 3,
              'sort': 2,
              'parentId': 3,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1010,
              'name': '角色修改',
              'permission': 'system:role:update',
              'type': 3,
              'sort': 3,
              'parentId': 3,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1011,
              'name': '角色删除',
              'permission': 'system:role:delete',
              'type': 3,
              'sort': 4,
              'parentId': 3,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1012,
              'name': '角色导出',
              'permission': 'system:role:export',
              'type': 3,
              'sort': 5,
              'parentId': 3,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1063,
              'name': '设置角色菜单权限',
              'permission': 'system:permission:assign-role-menu',
              'type': 3,
              'sort': 6,
              'parentId': 3,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609926824000
            },
            {
              'id': 1064,
              'name': '设置角色数据权限',
              'permission': 'system:permission:assign-role-data-scope',
              'type': 3,
              'sort': 7,
              'parentId': 3,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609926991000
            },
            {
              'id': 1065,
              'name': '设置用户角色',
              'permission': 'system:permission:assign-user-role',
              'type': 3,
              'sort': 8,
              'parentId': 3,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609986208000
            },
          ]
        },
        {
          component: 'system/menu/index',
          createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
          icon: 'menu',
          id: 4,
          path: 'menu',
          name: '菜单管理',
          componentName: 'SystemMenu',
          type: 2,
          sort: 4,
          status: 0,
          parentId: 1,
          children: [
            {
              'id': 1013,
              'name': '菜单查询',
              'permission': 'system:menu:query',
              'type': 3,
              'sort': 1,
              'parentId': 4,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1014,
              'name': '菜单新增',
              'permission': 'system:menu:create',
              'type': 3,
              'sort': 2,
              'parentId': 4,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1015,
              'name': '菜单修改',
              'permission': 'system:menu:update',
              'type': 3,
              'sort': 3,
              'parentId': 4,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1016,
              'name': '菜单删除',
              'permission': 'system:menu:delete',
              'type': 3,
              'sort': 4,
              'parentId': 4,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
          ]
        },
        {
          component: 'system/dept/index',
          createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
          icon: 'articleUser',
          id: 5,
          path: 'dept',
          name: '部门管理',
          componentName: 'SystemDept',
          type: 2,
          sort: 5,
          status: 0,
          parentId: 1,
          children: [
            {
              'id': 1017,
              'name': '部门查询',
              'permission': 'system:dept:query',
              'type': 3,
              'sort': 1,
              'parentId': 5,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1018,
              'name': '部门新增',
              'permission': 'system:dept:create',
              'type': 3,
              'sort': 2,
              'parentId': 5,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1019,
              'name': '部门修改',
              'permission': 'system:dept:update',
              'type': 3,
              'sort': 3,
              'parentId': 5,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1020,
              'name': '部门删除',
              'permission': 'system:dept:delete',
              'type': 3,
              'sort': 4,
              'parentId': 5,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
          ]
        },
        {
          component: 'system/post/index',
          createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
          icon: 'inboxUser',
          id: 6,
          path: 'post',
          name: '岗位管理',
          componentName: 'SystemPost',
          type: 2,
          sort: 6,
          status: 0,
          parentId: 1,
          children: [
            {
              'id': 1021,
              'name': '岗位查询',
              'permission': 'system:post:query',
              'type': 3,
              'sort': 1,
              'parentId': 6,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1022,
              'name': '岗位新增',
              'permission': 'system:post:create',
              'type': 3,
              'sort': 2,
              'parentId': 6,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1023,
              'name': '岗位修改',
              'permission': 'system:post:update',
              'type': 3,
              'sort': 3,
              'parentId': 6,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1024,
              'name': '岗位删除',
              'permission': 'system:post:delete',
              'type': 3,
              'sort': 4,
              'parentId': 6,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1025,
              'name': '岗位导出',
              'permission': 'system:post:export',
              'type': 3,
              'sort': 5,
              'parentId': 6,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
          ]
        },
        {
          component: 'system/dict/index',
          createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
          icon: 'book',
          id: 7,
          path: 'dict',
          name: '字典管理',
          componentName: 'SystemDict',
          type: 2,
          sort: 7,
          status: 0,
          parentId: 1,
          children: [
            {
              'id': 1026,
              'name': '字典查询',
              'permission': 'system:dict:query',
              'type': 3,
              'sort': 1,
              'parentId': 7,
              'path': '#',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1027,
              'name': '字典新增',
              'permission': 'system:dict:create',
              'type': 3,
              'sort': 2,
              'parentId': 7,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1028,
              'name': '字典修改',
              'permission': 'system:dict:update',
              'type': 3,
              'sort': 3,
              'parentId': 7,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1029,
              'name': '字典删除',
              'permission': 'system:dict:delete',
              'type': 3,
              'sort': 4,
              'parentId': 7,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1030,
              'name': '字典导出',
              'permission': 'system:dict:export',
              'type': 3,
              'sort': 5,
              'parentId': 7,
              'path': '#',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
          ]
        },
      ]
    }
  ],
  2: [
    {
      createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
      icon: 'setting',
      id: 1,
      path: '/system',
      redirect: '/system/user',
      name: '系统管理',
      componentName: 'System',
      type: 1,
      sort: 6,
      parentId: 0,
      status: 0,
      children: [
        {
          component: 'system/user/index',
          createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
          icon: 'user',
          id: 2,
          path: 'user',
          name: '用户管理',
          permission: 'system:user:list',
          componentName: 'SystemUser',
          type: 2,
          sort: 2,
          status: 0,
          parentId: 1,
          children: [
            {
              'id': 1001,
              'name': '用户查询',
              'permission': 'system:user:query',
              'type': 3,
              'sort': 1,
              'parentId': 2,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1002,
              'name': '用户新增',
              'permission': 'system:user:create',
              'type': 3,
              'sort': 2,
              'parentId': 2,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1003,
              'name': '用户修改',
              'permission': 'system:user:update',
              'type': 3,
              'sort': 3,
              'parentId': 2,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1004,
              'name': '用户删除',
              'permission': 'system:user:delete',
              'type': 3,
              'sort': 4,
              'parentId': 2,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1005,
              'name': '用户导出',
              'permission': 'system:user:export',
              'type': 3,
              'sort': 5,
              'parentId': 2,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1006,
              'name': '用户导入',
              'permission': 'system:user:import',
              'type': 3,
              'sort': 6,
              'parentId': 2,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1007,
              'name': '重置密码',
              'permission': 'system:user:update-password',
              'type': 3,
              'sort': 7,
              'parentId': 2,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            }
          ]
        },
      ]
    }
  ],
  3: [
    {
      createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
      icon: 'setting',
      id: 1,
      path: '/system',
      redirect: '/system/user',
      name: '系统管理',
      componentName: 'System',
      type: 1,
      sort: 6,
      status: 0,
      parentId: 0,
      children: [
        {
          component: 'system/dept/index',
          createTime: dayjs().format('YYYY-MM-DD HH:mm:ss'),
          icon: 'articleUser',
          id: 5,
          path: 'dept',
          name: '部门管理',
          componentName: 'SystemDept',
          type: 2,
          sort: 5,
          status: 0,
          parentId: 1,
          children: [
            {
              'id': 1017,
              'name': '部门查询',
              'permission': 'system:dept:query',
              'type': 3,
              'sort': 1,
              'parentId': 5,
              'path': '',
              'icon': '#',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1018,
              'name': '部门新增',
              'permission': 'system:dept:create',
              'type': 3,
              'sort': 2,
              'parentId': 5,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1019,
              'name': '部门修改',
              'permission': 'system:dept:update',
              'type': 3,
              'sort': 3,
              'parentId': 5,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
            {
              'id': 1020,
              'name': '部门删除',
              'permission': 'system:dept:delete',
              'type': 3,
              'sort': 4,
              'parentId': 5,
              'path': '',
              'icon': '',
              'component': '',
              'componentName': null,
              'status': 0,
              'visible': true,
              'keepAlive': true,
              'alwaysShow': true,
              'createTime': 1609837428000
            },
          ]
        },
      ]
    }
  ]
}
