packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/base/*
  - packages/@core/*
  - packages/effects/*
  - scripts/*
  - apps/*
  - playground
catalog:
  "@ant-design/icons-vue": ^7.0.1
  "@antfu/eslint-config": ^6.2.0
  "@ast-grep/napi": ^0.37.0
  "@changesets/git": ^3.0.4
  "@clack/prompts": ^0.11.0
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@commitlint/types": ^19.8.1
  "@faker-js/faker": ^10.1.0
  "@gx-design-vue/color-picker": ^0.2.0-beta.38
  "@gx-design-vue/icon": ^0.0.1
  "@gx-design-vue/image": ^0.2.0-beta.32
  "@gx-design-vue/pro-app": ^0.1.0-beta.33
  "@gx-design-vue/pro-card": ^0.2.0-beta.39
  "@gx-design-vue/pro-hooks": ^0.2.0-beta.55
  "@gx-design-vue/pro-layout": ^0.1.0-beta.169
  "@gx-design-vue/pro-layout-components": ^0.1.0-beta.20
  "@gx-design-vue/pro-modal": ^0.2.0-beta.37
  "@gx-design-vue/pro-provider": ^0.1.0-beta.130
  "@gx-design-vue/pro-table": ^0.2.0-beta.123
  "@gx-design-vue/pro-utils": ^0.2.0-beta.80
  "@gx-design-vue/pro-watermark": ^0.2.0-beta.15
  "@gx-design-vue/scrollbar": ^0.2.0-beta.21
  "@manypkg/get-packages": ^3.1.0
  "@pnpm/workspace.read-manifest": ^1000.2.5
  "@types/archiver": ^6.0.4
  "@types/jsonwebtoken": ^9.0.10
  "@types/lodash-es": ^4.17.12
  "@types/node": ^24.10.0
  "@types/nprogress": ^0.2.3
  "@types/qs": ^6.14.0
  "@vitejs/plugin-legacy": ^7.2.1
  "@vitejs/plugin-vue": ^6.0.1
  "@vitejs/plugin-vue-jsx": ^5.1.1
  "@vueuse/core": ^14.0.0
  "@vueuse/shared": ^14.0.0
  "@wangeditor-next/editor": ^5.6.47
  "@wangeditor-next/editor-for-vue": ^5.1.14
  ali-oss: ^6.23.0
  ant-design-vue: ^4.2.6
  archiver: ^7.0.1
  axios: ^1.13.2
  axios-mock-adapter: ^2.1.0
  bundle-import: ^0.0.2
  cac: ^6.7.14
  chalk: ^5.6.2
  chokidar: ^4.0.3
  circular-dependency-scanner: ^2.3.0
  color: ^5.0.2
  commitlint-plugin-function-rules: ^4.1.1
  consola: ^3.4.2
  cross-env: ^10.1.0
  crypto-js: ^4.2.0
  cz-git: ^1.12.0
  czg: ^1.12.0
  dayjs: ^1.11.19
  depcheck: ^1.4.7
  dotenv: ^16.6.1
  echarts: ^6.0.0
  execa: ^9.6.0
  find-up: ^8.0.0
  h3: ^1.5.3
  highlight.js: ^11.11.1
  husky: ^9.1.7
  jsonwebtoken: ^9.0.2
  lefthook: ^2.0.2
  less: ^4.4.0
  lint-staged: ^16.2.6
  lodash-es: ^4.17.21
  minimist: ^1.2.8
  nitropack: ^2.12.9
  nprogress: ^0.2.0
  ora: ^9.0.0
  path-to-regexp: ^8.3.0
  picocolors: ^1.1.1
  pinia: ^3.0.3
  pkg-types: ^2.3.0
  postcss: ^8.5.6
  postcss-html: ^1.8.0
  postcss-less: ^6.0.0
  publint: ^0.3.15
  qs: ^6.14.0
  rimraf: ^6.1.0
  rollup: ^4.53.1
  rollup-plugin-visualizer: ^6.0.5
  tailwind-merge: ^3.3.1
  tinyglobby: ^0.2.15
  turbo: ^2.6.0
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unocss: ^66.5.5
  unplugin-auto-import: ^20.2.0
  unplugin-turbo-console: ^2.2.0
  unplugin-vue-components: ^30.0.0
  vite: ^7.2.2
  vite-plugin-compression: 0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-fake-server: ^2.2.0
  vite-plugin-html: ^3.2.2
  vite-plugin-vue-devtools: ^8.0.3
  vitest: ^4.0.8
  vue: ^3.5.22
  vue-router: ^4.6.3
  vue-tsc: ^3.1.3
