// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GBars: typeof import('./../src/components/GDesign/Scrollbars')['default']
    GProTable: typeof import('./../src/components/GDesign/ProTable')['default']
    GProModal: typeof import('./../src/components/GDesign/ProModal')['default']
    GProPageContainer: typeof import('./../src/components/GDesign/ProLayout/components/PageContainer')['default']
  }
}

export { }
