export const colors: Record<string, any> = {
  base: 'var(--gx-color-text)',
  foreground: 'var(--gx-color-text-description)',
  quaternary: 'var(--gx-color-text-quaternary)',
  secondary: 'var(--gx-color-text-secondary)',
  heading: `var(--gx-color-text-heading)`,
  error: 'var(--gx-color-error)',
  'fill-alter': 'var(--gx-color-fill-alter)',
  'error-hover': 'var(--gx-color-error-hover)',
  success: 'var(--gx-color-success)',
  primary: 'var(--gx-color-primary)',
  split: 'var(--gx-color-split)',
  border: 'var(--gx-color-border)',
  'border-secondary': 'var(--gx-color-border-secondary)',
  background: `linear-gradient(var(--gx-color-bg-container), var(--gx-color-bg-layout) 28%)`,
  'background-container': `var(--gx-color-bg-container)`,
}
