/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ATag: typeof import('ant-design-vue/es')['Tag']
    AuthGroup: typeof import('./../src/components/layout/auth-group/index.vue')['default']
    ButtonTip: typeof import('./../src/components/layout/button-tip/index.vue')['default']
    ButtonTooltip: typeof import('@/components/layout/button-tip/index.vue')['default']
    Empty: typeof import('./../src/components/layout/empty/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamOutlined: typeof import('@ant-design/icons-vue')['TeamOutlined']
  }
}

// For TSX support
declare global {
  const AAvatar: typeof import('ant-design-vue/es')['Avatar']
  const AButton: typeof import('ant-design-vue/es')['Button']
  const ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
  const ACol: typeof import('ant-design-vue/es')['Col']
  const ADropdown: typeof import('ant-design-vue/es')['Dropdown']
  const AForm: typeof import('ant-design-vue/es')['Form']
  const AFormItem: typeof import('ant-design-vue/es')['FormItem']
  const AInput: typeof import('ant-design-vue/es')['Input']
  const AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
  const AMenu: typeof import('ant-design-vue/es')['Menu']
  const AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
  const AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
  const ARow: typeof import('ant-design-vue/es')['Row']
  const ASegmented: typeof import('ant-design-vue/es')['Segmented']
  const ASpin: typeof import('ant-design-vue/es')['Spin']
  const AStatistic: typeof import('ant-design-vue/es')['Statistic']
  const ATag: typeof import('ant-design-vue/es')['Tag']
  const AuthGroup: typeof import('./../src/components/layout/auth-group/index.vue')['default']
  const ButtonTip: typeof import('./../src/components/layout/button-tip/index.vue')['default']
  const ButtonTooltip: typeof import('@/components/layout/button-tip/index.vue')['default']
  const Empty: typeof import('./../src/components/layout/empty/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TeamOutlined: typeof import('@ant-design/icons-vue')['TeamOutlined']
}