export default {
  videoAllowType: [
    'mp4',
    'webm',
    'ogg'
  ],
  audioAllowType: [ 'mp3' ],
  filerobotImageZnch: {
    name: '图片编辑器',
    save: '保存',
    saveAs: '保存为新图片',
    back: '后退',
    loading: 'Loading...',
    resetOperations: '重置或者删除所有操作',
    changesLoseConfirmation: '所有更改都将丢失',
    changesLoseConfirmationHint: '你确定要继续吗?',
    cancel: '取消',
    continue: '继续',
    undoTitle: '撤消',
    redoTitle: '重置',
    showImageTitle: '显示原始图像',
    zoomInTitle: '放大',
    zoomOutTitle: '放小',
    toggleZoomMenuTitle: '切换缩放',
    adjustTab: '裁切',
    finetuneTab: '调整',
    filtersTab: '滤镜',
    watermarkTab: '水印',
    annotateTab: '编辑',
    resize: '缩放',
    resizeTab: '缩放',
    invalidImageError: '提供的图像无效.',
    uploadImageError: '上传图像时出错.',
    areNotImages: 'are not images',
    isNotImage: 'is not image',
    toBeUploaded: 'to be uploaded',
    cropTool: 'Crop',
    original: '原始比例',
    custom: '自定义',
    square: 'Square',
    landscape: 'Landscape',
    portrait: 'Portrait',
    ellipse: 'Ellipse',
    classicTv: '金典',
    cinemascope: 'Cinemascope',
    arrowTool: 'Arrow',
    blurTool: 'Blur',
    brightnessTool: 'Brightness',
    contrastTool: 'Contrast',
    ellipseTool: 'Ellipse',
    unFlipX: '恢复',
    flipX: '横向翻转',
    unFlipY: '恢复',
    flipY: '纵向翻转',
    hsvTool: 'HSV',
    hue: 'Hue',
    saturation: 'Saturation',
    value: 'Value',
    imageTool: '添加图片',
    importing: 'Importing...',
    addImage: '+ 添加图片',
    lineTool: 'Line',
    penTool: 'Pen',
    polygonTool: 'Polygon',
    sides: 'Sides',
    rectangleTool: 'Rectangle',
    cornerRadius: 'Corner Radius',
    resizeWidthTitle: 'Width in pixels',
    resizeHeightTitle: 'Height in pixels',
    toggleRatioLockTitle: 'Toggle ratio lock',
    reset: 'Reset',
    resetSize: 'Reset to original image size',
    rotateTool: '旋转',
    textTool: '添加字幕',
    textSpacings: 'Text spacings',
    textAlignment: 'Text alignment',
    fontFamily: 'Font family',
    size: 'Size',
    letterSpacing: '字间距',
    lineHeight: '行高',
    warmthTool: 'Warmth',
    addWatermark: '+ Add watermark',
    addWatermarkTitle: 'Choose the watermark type',
    uploadWatermark: 'Upload watermark',
    addWatermarkAsText: 'Add as text',
    padding: 'Padding',
    shadow: '阴影',
    horizontal: '水平',
    vertical: '垂直',
    blur: '滤镜',
    opacity: '透明度',
    position: 'Position',
    stroke: '描边',
    saveAsModalLabel: '保存图像为',
    extension: 'Extension',
    nameIsRequired: 'Name is required.',
    quality: 'Quality',
    imageDimensionsHoverTitle: 'Saved image size (width x height)',
    cropSizeLowerThanResizedWarning:
      'Note, the selected crop area is lower than the applied resize which might cause quality decrease',
    actualSize: 'Actual size (100%)',
    fitSize: 'Fit size',
  }
}
